default:
  outputs:
    dev:
      type: duckdb
      path: "../data/local.duckdb"
      threads: 16
      settings:
        preserve_insertion_order: false
        enable_object_cache: true
        enable_http_metadata_cache: true
  target: dev

config:
  send_anonymous_usage_stats: False
  use_colors: True
